services:
  backend:
    build:
      context: ./apps/backend
      dockerfile: Dockerfile
    container_name: monorepo-backend
    ports:
      - "3000:3000"
    volumes:
      - ./apps/backend:/app
      - /app/node_modules
    environment:
      - NODE_ENV=development
    command: npm run start:dev
    depends_on:
      - db

  frontend:
    build:
      context: ./apps/frontend
      dockerfile: Dockerfile
    container_name: monorepo-frontend
    ports:
      - "3001:3001"
    volumes:
      - ./apps/frontend:/app
      - /app/node_modules
    environment:
      - NODE_ENV=development
    command: npm run dev
    depends_on:
      - backend

  db:
    image: postgres:17-alpine
    container_name: monorepo-db
    ports:
      - "5432:5432"
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
      - POSTGRES_DB=mydb
    volumes:
      - postgres_data:/var/lib/postgresql/data

volumes:
  postgres_data:
